name: 🐞 Bug
description: File a bug/issue
title: "[X.Y] <Bug title>"
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
    - label: The bug was introduced in a recent release. Follow [what's next](https://github.com/Particular/KeepTheLightsOn/blob/master/bugs/bug-investigation.md#whats-next)
- type: markdown
  attributes:
    value: "# Description"
- type: textarea
  attributes:
    label: Observered Behavior
    description: A concise description of what you're observing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
    
- type: markdown
  attributes:
    value: "# Triage"
- type: markdown
  attributes:
    value: |
      | Category                       | Points     | Reason      |
      |--------------------------------|------------|-------------|
      | Severity                       |
- type: dropdown
    id: score
  attributes:
    options:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
  validations:
    required: true
